[package]
name = "quic_protocol"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
quinn = { version = "0.11.1" }
rustls = { version = "0.21" }
rcgen = "0.13"